//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateNightStupidities.XorPersist.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LateNightStupidities.XorPersist.Properties.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XorClass attribute is missing on type {0}. Add the attribute to the class declaration..
        /// </summary>
        internal static string ClassAttributeMissingException {
            get {
                return ResourceManager.GetString("ClassAttributeMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve reference at &apos;{0}&apos;. Failed to find object with XorId &apos;{1}&apos;..
        /// </summary>
        internal static string CouldNotResolveReferenceException {
            get {
                return ResourceManager.GetString("CouldNotResolveReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameterless constructor is missing on type {0}. XorPersist could not instantiate this class. Define a public parameterless constructor at this type. Alternatively, a method with the following signature that returns an instance of the type can be defined: &quot;static object _XorCreate()&quot;..
        /// </summary>
        internal static string CtorMissingException {
            get {
                return ResourceManager.GetString("CtorMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found duplicate XorClass name &apos;{0}&apos;. Type of existing entry: &apos;{1}, Assembly &lt;{3}&gt;&apos;. Type of duplicate entry: &apos;{2}, Assembly &lt;{4}&gt;&apos;..
        /// </summary>
        internal static string DuplicateXorClassNameException {
            get {
                return ResourceManager.GetString("DuplicateXorClassNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type ({0}) is not supported by XorPersist. Class: {1}. Class Property: {3}. XorPersist Property: {2}..
        /// </summary>
        internal static string PropertyTypeNotSupportedException {
            get {
                return ResourceManager.GetString("PropertyTypeNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type ({0}) is not supported by XorPersist. Problem loading value from element &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyTypeNotSupportedException2 {
            get {
                return ResourceManager.GetString("PropertyTypeNotSupportedException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data does not conform to the XorPersist XML schema. Line {0}, Position {1}: {2}.
        /// </summary>
        internal static string SchemaValidationException {
            get {
                return ResourceManager.GetString("SchemaValidationException", resourceCulture);
            }
        }
    }
}
